# Generated by Django 3.2.6 on 2021-08-29 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_image', models.ImageField(upload_to='delicious/')),
                ('price', models.CharField(blank=True, max_length=100)),
                ('offer_price', models.CharField(blank=True, max_length=100)),
                ('des', models.TextField(blank=True, max_length=2000)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('V', 'Veg'), ('N', 'Nonveg'), ('D', 'Dessert')], max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious.order')),
            ],
        ),
    ]
