# Generated by Django 3.2.6 on 2021-08-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0002_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
