# Generated by Django 3.2.6 on 2021-08-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0004_auto_20210830_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodVlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('founder_image', models.ImageField(blank=True, upload_to='delicious/')),
                ('founder_des', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
