# Generated by Django 3.2.6 on 2021-08-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0005_foodvlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodvlogs',
            name='founder_des',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='foodvlogs',
            name='name',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
