# Generated by Django 3.2.6 on 2021-09-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0006_auto_20210830_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Founders',
        ),
    ]
