# Generated by Django 3.2.6 on 2021-09-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0007_delete_founders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_image', models.ImageField(upload_to='delicious/')),
                ('ex_name', models.CharField(blank=True, max_length=200)),
                ('ex_des', models.TextField(blank=True, max_length=2000)),
            ],
        ),
    ]
