# Generated by Django 3.2.6 on 2021-09-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0009_executivedetails_ex_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_image', models.ImageField(upload_to='delicious/')),
                ('ad_name', models.TextField(max_length=1000)),
                ('ad_des', models.TextField(max_length=2000)),
            ],
        ),
    ]
