# Generated by Django 3.2.6 on 2021-09-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0010_advertisements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='ad_des',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='ad_name',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
